//
//  SongGeneratedMetaData.swift
//  reDiscover
//
//  Created by Teo on 12/05/15.
//  Copyright (c) 2015 Teo Sartori. All rights reserved.
//

import Foundation

/** 
Metadata that has been generated by reDiscover.
Includes fingerprint, UUId, Sweetspots, selected Sweetspot, etc.
*/
struct SongGeneratedMetaData {
    let UUId: String
}