//
//  SongGeneratedMetaData.swift
//  reDiscover
//
//  Created by Teo on 12/05/15.
//  Copyright (c) 2015 Teo Sartori. All rights reserved.
//

import Foundation

/** 
Metadata that has been generated by reDiscover.
Includes fingerprint, UUId, Sweetspots, selected Sweetspot, etc.
*/
struct SongGeneratedMetaData {
    let UUId: String?
    let URLString: String
//    let songID: SongId
//    let selectedSweetSpot: Float
//    let sweetSpots: [SweetSpot]?
//    let metadata: SongCommonMetaData?
//    let artID: String?
//    let fingerPrint: String?
//    let songReleases: NSData?
//    let RelId: String?
}